### ISSUE TITLE
SideBar

### ISSUE THREAD

**Issue by alexojo** [Claudiars20/PSG.Frontend#2]
- [x] Desabilitar funciones de SideBar Tutor (funciones que quedan - fichas tutoria **(estudiantes a cargo)** y sesiones)
- [x] .Boton  Feedback (SideBar) - Redirecciona a Form Google

**Comment by ManuelVelarde2212** [comment]
Feedback button created satisfactory

**Comment by Cucho145U** [comment]
Funciones deshabilitadas correctamente
