### ISSUE TITLE
Formulario Ver Sesion

### ISSUE THREAD

**Issue by alexojo** [Claudiars20/PSG.Frontend#4]
- [x] Boton Visualizar Sesion
- [x] Formulario de Sesion
- [x] Ver Sesion con sus descripciones
- [x] Realizar conexiones con el backend, para recuperar los datos de las sesiones

**Comment by Claudiars20** [comment]
- [ ] Ver sesiones con sus descripciones

**Comment by Claudiars20** [comment]
Completado

**Comment by Claudiars20** [comment]
- [ ] Funcionalidad enviar referencias(checkbox) concatenadas al POST de sesion

**Comment by Claudiars20** [comment]
Culminado el domingo 14 de nov.
